language: java

install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - . ./install-jdk.sh -F 10 -L GPL

services:
  - docker

script:
  - mvn package
  - docker build -t jpodeszwik/xml-analyzer .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push jpodeszwik/xml-analyzer

